name: generators

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build:
  source_gen:
  annotations:
    git:
      url: https://github.com/definev/vil.git
      path: annotations

dev_dependencies:
  build_test:
  build_runner:
  analyzer:
