name: vil

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  annotations:
    git:
      url: https://github.com/definev/vil.git
      path: annotations

dev_dependencies:
  test:
  build_runner:
  generators:
    git:
      url: https://github.com/definev/vil.git
      path: generators
